/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account/': typeof AccountIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account': typeof AccountIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account/': typeof AccountIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/new-arrivals'
    | '/order-confirmation'
    | '/returns'
    | '/sale'
    | '/search'
    | '/shipping'
    | '/wishlist'
    | '/account/orders'
    | '/collections/$slug'
    | '/product/$slug'
    | '/shop/$category'
    | '/account/'
    | '/collections/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/new-arrivals'
    | '/order-confirmation'
    | '/returns'
    | '/sale'
    | '/search'
    | '/shipping'
    | '/wishlist'
    | '/account/orders'
    | '/collections/$slug'
    | '/product/$slug'
    | '/shop/$category'
    | '/account'
    | '/collections'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/new-arrivals'
    | '/order-confirmation'
    | '/returns'
    | '/sale'
    | '/search'
    | '/shipping'
    | '/wishlist'
    | '/account/orders'
    | '/collections/$slug'
    | '/product/$slug'
    | '/shop/$category'
    | '/account/'
    | '/collections/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  ReturnsRoute: typeof ReturnsRoute
  SaleRoute: typeof SaleRoute
  SearchRoute: typeof SearchRoute
  ShippingRoute: typeof ShippingRoute
  WishlistRoute: typeof WishlistRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ShopCategoryRoute: typeof ShopCategoryRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/shop/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  ReturnsRoute: ReturnsRoute,
  SaleRoute: SaleRoute,
  SearchRoute: SearchRoute,
  ShippingRoute: ShippingRoute,
  WishlistRoute: WishlistRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ShopCategoryRoute: ShopCategoryRoute,
  AccountIndexRoute: AccountIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
