/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSalesRouteImport } from './routes/admin/sales'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminHelpRouteImport } from './routes/admin/help'
import { Route as AdminDiscountsRouteImport } from './routes/admin/discounts'
import { Route as AdminDeliveryRouteImport } from './routes/admin/delivery'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminAppearanceRouteImport } from './routes/admin/appearance'
import { Route as AdminActivityLogsRouteImport } from './routes/admin/activity-logs'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppearanceRoute = AdminAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/appearance': typeof AdminAppearanceRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/new-arrivals'
    | '/order-confirmation'
    | '/returns'
    | '/sale'
    | '/search'
    | '/shipping'
    | '/track-order'
    | '/wishlist'
    | '/account/orders'
    | '/admin/activity-logs'
    | '/admin/appearance'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/discounts'
    | '/admin/help'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/sales'
    | '/admin/settings'
    | '/collections/$slug'
    | '/product/$slug'
    | '/shop/$category'
    | '/account'
    | '/admin/'
    | '/collections'
    | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/new-arrivals'
    | '/order-confirmation'
    | '/returns'
    | '/sale'
    | '/search'
    | '/shipping'
    | '/track-order'
    | '/wishlist'
    | '/account/orders'
    | '/admin/activity-logs'
    | '/admin/appearance'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/discounts'
    | '/admin/help'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/sales'
    | '/admin/settings'
    | '/collections/$slug'
    | '/product/$slug'
    | '/shop/$category'
    | '/account'
    | '/admin'
    | '/collections'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/new-arrivals'
    | '/order-confirmation'
    | '/returns'
    | '/sale'
    | '/search'
    | '/shipping'
    | '/track-order'
    | '/wishlist'
    | '/account/orders'
    | '/admin/activity-logs'
    | '/admin/appearance'
    | '/admin/customers'
    | '/admin/delivery'
    | '/admin/discounts'
    | '/admin/help'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/sales'
    | '/admin/settings'
    | '/collections/$slug'
    | '/product/$slug'
    | '/shop/$category'
    | '/account/'
    | '/admin/'
    | '/collections/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  ReturnsRoute: typeof ReturnsRoute
  SaleRoute: typeof SaleRoute
  SearchRoute: typeof SearchRoute
  ShippingRoute: typeof ShippingRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WishlistRoute: typeof WishlistRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ShopCategoryRoute: typeof ShopCategoryRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity-logs': {
      id: '/admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appearance': {
      id: '/admin/appearance'
      path: '/appearance'
      fullPath: '/admin/appearance'
      preLoaderRoute: typeof AdminAppearanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/shop/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/about' {
  const createFileRoute: CreateFileRoute<
    '/about',
    FileRoutesByPath['/about']['parentRoute'],
    FileRoutesByPath['/about']['id'],
    FileRoutesByPath['/about']['path'],
    FileRoutesByPath['/about']['fullPath']
  >
}
declare module './routes/admin' {
  const createFileRoute: CreateFileRoute<
    '/admin',
    FileRoutesByPath['/admin']['parentRoute'],
    FileRoutesByPath['/admin']['id'],
    FileRoutesByPath['/admin']['path'],
    FileRoutesByPath['/admin']['fullPath']
  >
}
declare module './routes/cart' {
  const createFileRoute: CreateFileRoute<
    '/cart',
    FileRoutesByPath['/cart']['parentRoute'],
    FileRoutesByPath['/cart']['id'],
    FileRoutesByPath['/cart']['path'],
    FileRoutesByPath['/cart']['fullPath']
  >
}
declare module './routes/checkout' {
  const createFileRoute: CreateFileRoute<
    '/checkout',
    FileRoutesByPath['/checkout']['parentRoute'],
    FileRoutesByPath['/checkout']['id'],
    FileRoutesByPath['/checkout']['path'],
    FileRoutesByPath['/checkout']['fullPath']
  >
}
declare module './routes/contact' {
  const createFileRoute: CreateFileRoute<
    '/contact',
    FileRoutesByPath['/contact']['parentRoute'],
    FileRoutesByPath['/contact']['id'],
    FileRoutesByPath['/contact']['path'],
    FileRoutesByPath['/contact']['fullPath']
  >
}
declare module './routes/faq' {
  const createFileRoute: CreateFileRoute<
    '/faq',
    FileRoutesByPath['/faq']['parentRoute'],
    FileRoutesByPath['/faq']['id'],
    FileRoutesByPath['/faq']['path'],
    FileRoutesByPath['/faq']['fullPath']
  >
}
declare module './routes/new-arrivals' {
  const createFileRoute: CreateFileRoute<
    '/new-arrivals',
    FileRoutesByPath['/new-arrivals']['parentRoute'],
    FileRoutesByPath['/new-arrivals']['id'],
    FileRoutesByPath['/new-arrivals']['path'],
    FileRoutesByPath['/new-arrivals']['fullPath']
  >
}
declare module './routes/order-confirmation' {
  const createFileRoute: CreateFileRoute<
    '/order-confirmation',
    FileRoutesByPath['/order-confirmation']['parentRoute'],
    FileRoutesByPath['/order-confirmation']['id'],
    FileRoutesByPath['/order-confirmation']['path'],
    FileRoutesByPath['/order-confirmation']['fullPath']
  >
}
declare module './routes/returns' {
  const createFileRoute: CreateFileRoute<
    '/returns',
    FileRoutesByPath['/returns']['parentRoute'],
    FileRoutesByPath['/returns']['id'],
    FileRoutesByPath['/returns']['path'],
    FileRoutesByPath['/returns']['fullPath']
  >
}
declare module './routes/sale' {
  const createFileRoute: CreateFileRoute<
    '/sale',
    FileRoutesByPath['/sale']['parentRoute'],
    FileRoutesByPath['/sale']['id'],
    FileRoutesByPath['/sale']['path'],
    FileRoutesByPath['/sale']['fullPath']
  >
}
declare module './routes/search' {
  const createFileRoute: CreateFileRoute<
    '/search',
    FileRoutesByPath['/search']['parentRoute'],
    FileRoutesByPath['/search']['id'],
    FileRoutesByPath['/search']['path'],
    FileRoutesByPath['/search']['fullPath']
  >
}
declare module './routes/shipping' {
  const createFileRoute: CreateFileRoute<
    '/shipping',
    FileRoutesByPath['/shipping']['parentRoute'],
    FileRoutesByPath['/shipping']['id'],
    FileRoutesByPath['/shipping']['path'],
    FileRoutesByPath['/shipping']['fullPath']
  >
}
declare module './routes/track-order' {
  const createFileRoute: CreateFileRoute<
    '/track-order',
    FileRoutesByPath['/track-order']['parentRoute'],
    FileRoutesByPath['/track-order']['id'],
    FileRoutesByPath['/track-order']['path'],
    FileRoutesByPath['/track-order']['fullPath']
  >
}
declare module './routes/wishlist' {
  const createFileRoute: CreateFileRoute<
    '/wishlist',
    FileRoutesByPath['/wishlist']['parentRoute'],
    FileRoutesByPath['/wishlist']['id'],
    FileRoutesByPath['/wishlist']['path'],
    FileRoutesByPath['/wishlist']['fullPath']
  >
}
declare module './routes/account.orders' {
  const createFileRoute: CreateFileRoute<
    '/account/orders',
    FileRoutesByPath['/account/orders']['parentRoute'],
    FileRoutesByPath['/account/orders']['id'],
    FileRoutesByPath['/account/orders']['path'],
    FileRoutesByPath['/account/orders']['fullPath']
  >
}
declare module './routes/admin/activity-logs' {
  const createFileRoute: CreateFileRoute<
    '/admin/activity-logs',
    FileRoutesByPath['/admin/activity-logs']['parentRoute'],
    FileRoutesByPath['/admin/activity-logs']['id'],
    FileRoutesByPath['/admin/activity-logs']['path'],
    FileRoutesByPath['/admin/activity-logs']['fullPath']
  >
}
declare module './routes/admin/appearance' {
  const createFileRoute: CreateFileRoute<
    '/admin/appearance',
    FileRoutesByPath['/admin/appearance']['parentRoute'],
    FileRoutesByPath['/admin/appearance']['id'],
    FileRoutesByPath['/admin/appearance']['path'],
    FileRoutesByPath['/admin/appearance']['fullPath']
  >
}
declare module './routes/admin/customers' {
  const createFileRoute: CreateFileRoute<
    '/admin/customers',
    FileRoutesByPath['/admin/customers']['parentRoute'],
    FileRoutesByPath['/admin/customers']['id'],
    FileRoutesByPath['/admin/customers']['path'],
    FileRoutesByPath['/admin/customers']['fullPath']
  >
}
declare module './routes/admin/delivery' {
  const createFileRoute: CreateFileRoute<
    '/admin/delivery',
    FileRoutesByPath['/admin/delivery']['parentRoute'],
    FileRoutesByPath['/admin/delivery']['id'],
    FileRoutesByPath['/admin/delivery']['path'],
    FileRoutesByPath['/admin/delivery']['fullPath']
  >
}
declare module './routes/admin/discounts' {
  const createFileRoute: CreateFileRoute<
    '/admin/discounts',
    FileRoutesByPath['/admin/discounts']['parentRoute'],
    FileRoutesByPath['/admin/discounts']['id'],
    FileRoutesByPath['/admin/discounts']['path'],
    FileRoutesByPath['/admin/discounts']['fullPath']
  >
}
declare module './routes/admin/help' {
  const createFileRoute: CreateFileRoute<
    '/admin/help',
    FileRoutesByPath['/admin/help']['parentRoute'],
    FileRoutesByPath['/admin/help']['id'],
    FileRoutesByPath['/admin/help']['path'],
    FileRoutesByPath['/admin/help']['fullPath']
  >
}
declare module './routes/admin/orders' {
  const createFileRoute: CreateFileRoute<
    '/admin/orders',
    FileRoutesByPath['/admin/orders']['parentRoute'],
    FileRoutesByPath['/admin/orders']['id'],
    FileRoutesByPath['/admin/orders']['path'],
    FileRoutesByPath['/admin/orders']['fullPath']
  >
}
declare module './routes/admin/products' {
  const createFileRoute: CreateFileRoute<
    '/admin/products',
    FileRoutesByPath['/admin/products']['parentRoute'],
    FileRoutesByPath['/admin/products']['id'],
    FileRoutesByPath['/admin/products']['path'],
    FileRoutesByPath['/admin/products']['fullPath']
  >
}
declare module './routes/admin/sales' {
  const createFileRoute: CreateFileRoute<
    '/admin/sales',
    FileRoutesByPath['/admin/sales']['parentRoute'],
    FileRoutesByPath['/admin/sales']['id'],
    FileRoutesByPath['/admin/sales']['path'],
    FileRoutesByPath['/admin/sales']['fullPath']
  >
}
declare module './routes/admin/settings' {
  const createFileRoute: CreateFileRoute<
    '/admin/settings',
    FileRoutesByPath['/admin/settings']['parentRoute'],
    FileRoutesByPath['/admin/settings']['id'],
    FileRoutesByPath['/admin/settings']['path'],
    FileRoutesByPath['/admin/settings']['fullPath']
  >
}
declare module './routes/collections.$slug' {
  const createFileRoute: CreateFileRoute<
    '/collections/$slug',
    FileRoutesByPath['/collections/$slug']['parentRoute'],
    FileRoutesByPath['/collections/$slug']['id'],
    FileRoutesByPath['/collections/$slug']['path'],
    FileRoutesByPath['/collections/$slug']['fullPath']
  >
}
declare module './routes/product.$slug' {
  const createFileRoute: CreateFileRoute<
    '/product/$slug',
    FileRoutesByPath['/product/$slug']['parentRoute'],
    FileRoutesByPath['/product/$slug']['id'],
    FileRoutesByPath['/product/$slug']['path'],
    FileRoutesByPath['/product/$slug']['fullPath']
  >
}
declare module './routes/shop.$category' {
  const createFileRoute: CreateFileRoute<
    '/shop/$category',
    FileRoutesByPath['/shop/$category']['parentRoute'],
    FileRoutesByPath['/shop/$category']['id'],
    FileRoutesByPath['/shop/$category']['path'],
    FileRoutesByPath['/shop/$category']['fullPath']
  >
}
declare module './routes/account.index' {
  const createFileRoute: CreateFileRoute<
    '/account/',
    FileRoutesByPath['/account/']['parentRoute'],
    FileRoutesByPath['/account/']['id'],
    FileRoutesByPath['/account/']['path'],
    FileRoutesByPath['/account/']['fullPath']
  >
}
declare module './routes/admin/index' {
  const createFileRoute: CreateFileRoute<
    '/admin/',
    FileRoutesByPath['/admin/']['parentRoute'],
    FileRoutesByPath['/admin/']['id'],
    FileRoutesByPath['/admin/']['path'],
    FileRoutesByPath['/admin/']['fullPath']
  >
}
declare module './routes/collections.index' {
  const createFileRoute: CreateFileRoute<
    '/collections/',
    FileRoutesByPath['/collections/']['parentRoute'],
    FileRoutesByPath['/collections/']['id'],
    FileRoutesByPath['/collections/']['path'],
    FileRoutesByPath['/collections/']['fullPath']
  >
}
declare module './routes/shop.index' {
  const createFileRoute: CreateFileRoute<
    '/shop/',
    FileRoutesByPath['/shop/']['parentRoute'],
    FileRoutesByPath['/shop/']['id'],
    FileRoutesByPath['/shop/']['path'],
    FileRoutesByPath['/shop/']['fullPath']
  >
}

interface AdminRouteChildren {
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminAppearanceRoute: typeof AdminAppearanceRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminAppearanceRoute: AdminAppearanceRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  ReturnsRoute: ReturnsRoute,
  SaleRoute: SaleRoute,
  SearchRoute: SearchRoute,
  ShippingRoute: ShippingRoute,
  TrackOrderRoute: TrackOrderRoute,
  WishlistRoute: WishlistRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ShopCategoryRoute: ShopCategoryRoute,
  AccountIndexRoute: AccountIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
